blank_issues_enabled: false
contact_links:
  - name: Telegram Contact
    url: https://t.me/cjh0613
    about: Ask questions and discuss with me via Telegram.
  - name: QQ 联系
    url: http://sighttp.qq.com/authd?IDKEY=4d5d36c19d4b64b91e4074144124b486759e276fa30b8abc
    about: 通过 QQ 联系我，来讨论此项目
